spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/microservices?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimeZone=UTC
    username: vuhso04
    password: 123abc
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: /
  data:
    redis:
      host: localhost
      port: 6379
      password: 123abc
server:
  port: 8088

